//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("task1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13780
        ///6284
        ///-27078
        ///9070
        ///-303
        ///-30356
        ///-10734
        ///8670
        ///10498
        ///-11992
        ///31658
        ///-18481
        ///15975
        ///17158
        ///19856
        ///-1538
        ///-21551
        ///8332
        ///-11563
        ///1397
        ///11748
        ///-17397
        ///4798
        ///-15492
        ///12524
        ///-11887
        ///-28646
        ///-13095
        ///-19010
        ///-3434
        ///30312
        ///6344
        ///18183
        ///-30859
        ///16523
        ///-26323
        ///20398
        ///-9628
        ///-28080
        ///-27707
        ///9656
        ///-9318
        ///18544
        ///-30385
        ///27363
        ///-27518
        ///-26332
        ///-16393
        ///25432
        ///-926
        ///-13792
        ///-25034
        ///-7053
        ///18477
        ///12589
        ///10050
        ///16666
        ///12102
        ///-24648
        ///13392
        ///32049
        ///6029
        ///3566
        ///-30914
        ///5770
        ///-7688
        ///27123
        ///-21391
        ///-22595
        ///2372
        ///-20410
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
    }
}
